import { contextBridge, ipcRenderer } from "electron";
import type {
  AppInfo,
  BackupResult,
  BackupScheduleStatus,
  BusinessSettings,
  ChangePasswordInput,
  CloudBackupRecord,
  CloudDeviceApprovalInput,
  CloudDeviceOwnerCredentials,
  Customer,
  DataHealthReport,
  DateRangePreset,
  DeveloperDiagnostics,
  DriveBackupResult,
  DriveConnectionStatus,
  EnquiryFollowupInput,
  EnquiryInput,
  EnquiryStatus,
  ExpenseInput,
  InventoryItem,
  InventoryMovementInput,
  InventoryPurchaseInput,
  InvoiceAppendItemInput,
  InvoiceCancelInput,
  InvoiceCreateInput,
  InvoiceDraftSaveInput,
  JobCardInput,
  JobCardPhotoType,
  JobCardStatus,
  LoginInput,
  PrintInput,
  PurchaseRecordInput,
  QuotationSaveInput,
  QuotationStatusInput,
  RecordPaymentInput,
  ReportDateFilter,
  ReportExportKind,
  SavePdfInput,
  SaveAccessRoleInput,
  SaveUserInput,
  SafeRepairCode,
  SafeRepairResult,
  ServiceItem,
  SyncConnectInput,
  SyncConflictResolution,
  SetupOwnerInput,
  Supplier,
  VehicleType,
  WhatsAppShareInput
} from "../shared/types";

contextBridge.exposeInMainWorld("autocare", {
  authStatus: () => ipcRenderer.invoke("auth:status"),
  setupOwner: (input: SetupOwnerInput) => ipcRenderer.invoke("auth:setupOwner", input),
  login: (input: LoginInput) => ipcRenderer.invoke("auth:login", input),
  existingBusinessStatus: () => ipcRenderer.invoke("auth:existingBusinessStatus"),
  connectExistingBusiness: (input: SyncConnectInput) => ipcRenderer.invoke("auth:connectExistingBusiness", input),
  checkExistingBusinessApproval: () => ipcRenderer.invoke("auth:checkExistingBusinessApproval"),
  logout: () => ipcRenderer.invoke("auth:logout"),
  listUsers: () => ipcRenderer.invoke("users:list"),
  saveUser: (input: SaveUserInput) => ipcRenderer.invoke("users:save", input),
  deactivateUser: (id: string) => ipcRenderer.invoke("users:deactivate", id),
  listAccessRoles: () => ipcRenderer.invoke("roles:list"),
  saveAccessRole: (input: SaveAccessRoleInput) => ipcRenderer.invoke("roles:save", input),
  deactivateAccessRole: (id: string) => ipcRenderer.invoke("roles:deactivate", id),
  changePassword: (input: ChangePasswordInput) => ipcRenderer.invoke("users:changePassword", input),
  dashboard: () => ipcRenderer.invoke("dashboard:get"),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  saveSettings: (settings: Partial<BusinessSettings>) => ipcRenderer.invoke("settings:save", settings),
  pickInvoiceAsset: (kind: "logo" | "signature" | "watermark") => ipcRenderer.invoke("settings:pickAsset", kind),
  readInvoiceAsset: (filePath?: string) => ipcRenderer.invoke("settings:readAsset", filePath),
  pickInvoiceLogo: () => ipcRenderer.invoke("settings:pickLogo"),
  readInvoiceLogo: (filePath?: string) => ipcRenderer.invoke("settings:readLogo", filePath),
  listServices: (includeInactive?: boolean) => ipcRenderer.invoke("services:list", includeInactive),
  saveService: (service: Partial<ServiceItem> & Pick<ServiceItem, "name">) => ipcRenderer.invoke("services:save", service),
  deactivateService: (id: string) => ipcRenderer.invoke("services:deactivate", id),
  inventoryDashboard: () => ipcRenderer.invoke("inventory:dashboard"),
  listInventoryItems: (includeInactive?: boolean) => ipcRenderer.invoke("inventory:items", includeInactive),
  saveInventoryItem: (item: Partial<InventoryItem> & Pick<InventoryItem, "name">) => ipcRenderer.invoke("inventory:saveItem", item),
  deactivateInventoryItem: (id: string) => ipcRenderer.invoke("inventory:deactivateItem", id),
  listSuppliers: () => ipcRenderer.invoke("inventory:suppliers"),
  saveSupplier: (supplier: Partial<Supplier> & Pick<Supplier, "name">) => ipcRenderer.invoke("inventory:saveSupplier", supplier),
  addInventoryPurchase: (input: InventoryPurchaseInput) => ipcRenderer.invoke("inventory:addPurchase", input),
  addInventoryMovement: (input: InventoryMovementInput) => ipcRenderer.invoke("inventory:addMovement", input),
  listInventoryBatches: (itemId?: string) => ipcRenderer.invoke("inventory:batches", itemId),
  listInventoryMovements: (itemId?: string) => ipcRenderer.invoke("inventory:movements", itemId),
  listPurchaseRecords: (query?: string) => ipcRenderer.invoke("purchaseRecords:list", query),
  savePurchaseRecord: (input: PurchaseRecordInput, documentPaths?: string[]) => ipcRenderer.invoke("purchaseRecords:save", input, documentPaths),
  deletePurchaseRecord: (id: string) => ipcRenderer.invoke("purchaseRecords:delete", id),
  pickPurchaseRecordDocuments: () => ipcRenderer.invoke("purchaseRecords:pickDocuments"),
  readPurchaseRecordDocument: (fileId: string, localPath?: string) => ipcRenderer.invoke("purchaseRecords:readDocument", fileId, localPath),
  getServiceRecipe: (serviceId: string) => ipcRenderer.invoke("services:recipe:get", serviceId),
  saveServiceRecipe: (serviceId: string, rows: Array<{ inventoryItemId: string; quantity: number }>) =>
    ipcRenderer.invoke("services:recipe:save", serviceId, rows),
  enquiryDashboard: () => ipcRenderer.invoke("enquiries:dashboard"),
  listEnquiries: (filter?: { query?: string; status?: EnquiryStatus | "open" | "followups" }) =>
    ipcRenderer.invoke("enquiries:list", filter),
  saveEnquiry: (input: EnquiryInput) => ipcRenderer.invoke("enquiries:save", input),
  listEnquiryFollowups: (enquiryId: string) => ipcRenderer.invoke("enquiries:followups", enquiryId),
  addEnquiryFollowup: (input: EnquiryFollowupInput) => ipcRenderer.invoke("enquiries:addFollowup", input),
  convertEnquiryToCustomer: (enquiryId: string) => ipcRenderer.invoke("enquiries:convert", enquiryId),
  jobCardDashboard: () => ipcRenderer.invoke("jobCards:dashboard"),
  listJobCards: (filter?: { query?: string; status?: JobCardStatus | "today" | "open" | "approval" | "progress" | "ready" | "closed" }) =>
    ipcRenderer.invoke("jobCards:list", filter),
  getJobCard: (id: string) => ipcRenderer.invoke("jobCards:get", id),
  saveJobCard: (input: JobCardInput) => ipcRenderer.invoke("jobCards:save", input),
  updateJobCardStatus: (input: { jobCardId: string; status: JobCardStatus; note?: string }) =>
    ipcRenderer.invoke("jobCards:updateStatus", input),
  saveJobCardChecklist: (jobCardId: string, rows: Array<{ id: string; checked: boolean }>) =>
    ipcRenderer.invoke("jobCards:saveChecklist", jobCardId, rows),
  getJobCardSettings: () => ipcRenderer.invoke("jobCards:getSettings"),
  saveJobCardSettings: (input: { defaultChecklist: string[] }) => ipcRenderer.invoke("jobCards:saveSettings", input),
  pickJobCardPhotos: (jobCardId: string, type: JobCardPhotoType) => ipcRenderer.invoke("jobCards:pickPhotos", jobCardId, type),
  removeJobCardPhoto: (photoId: string) => ipcRenderer.invoke("jobCards:removePhoto", photoId),
  updateJobCardPhotoCaption: (photoId: string, caption: string) => ipcRenderer.invoke("jobCards:updatePhotoCaption", photoId, caption),
  convertJobCardToInvoice: (jobCardId: string) => ipcRenderer.invoke("jobCards:convertToInvoice", jobCardId),
  listCustomers: () => ipcRenderer.invoke("customers:list"),
  saveCustomer: (customer: Partial<Customer> & Pick<Customer, "name">) => ipcRenderer.invoke("customers:save", customer),
  saveVehicle: (vehicle: {
    id?: string;
    customerId: string;
    vehicleType?: VehicleType;
    registrationNumber: string;
    make?: string;
    model?: string;
    color?: string;
  }) => ipcRenderer.invoke("vehicles:save", vehicle),
  createInvoice: (input: InvoiceCreateInput) => ipcRenderer.invoke("invoices:create", input),
  listInvoices: (query?: string) => ipcRenderer.invoke("invoices:list", query),
  getInvoice: (id: string) => ipcRenderer.invoke("invoices:get", id),
  listInvoiceDrafts: () => ipcRenderer.invoke("invoiceDrafts:list"),
  getInvoiceDraft: (id: string) => ipcRenderer.invoke("invoiceDrafts:get", id),
  saveInvoiceDraft: (input: InvoiceDraftSaveInput) => ipcRenderer.invoke("invoiceDrafts:save", input),
  discardInvoiceDraft: (id: string) => ipcRenderer.invoke("invoiceDrafts:discard", id),
  finalizeInvoiceDraft: (id: string) => ipcRenderer.invoke("invoiceDrafts:finalize", id),
  cancelInvoice: (input: InvoiceCancelInput) => ipcRenderer.invoke("invoices:cancel", input),
  appendInvoiceItem: (input: InvoiceAppendItemInput) => ipcRenderer.invoke("invoices:appendItem", input),
  finalizePendingCloudInvoice: (invoiceId: string) => ipcRenderer.invoke("invoices:finalizePendingCloud", invoiceId),
  movePendingCloudInvoiceToDraft: (invoiceId: string) => ipcRenderer.invoke("invoices:movePendingCloudToDraft", invoiceId),
  createReplacementDraft: (invoiceId: string) => ipcRenderer.invoke("invoices:createReplacementDraft", invoiceId),
  createAddonDraft: (invoiceId: string) => ipcRenderer.invoke("invoices:createAddonDraft", invoiceId),
  recordPayment: (input: RecordPaymentInput) => ipcRenderer.invoke("payments:record", input),
  listQuotations: (query?: string) => ipcRenderer.invoke("quotations:list", query),
  getQuotation: (id: string) => ipcRenderer.invoke("quotations:get", id),
  saveQuotation: (input: QuotationSaveInput) => ipcRenderer.invoke("quotations:save", input),
  updateQuotationStatus: (input: QuotationStatusInput) => ipcRenderer.invoke("quotations:updateStatus", input),
  convertQuotationToInvoice: (id: string) => ipcRenderer.invoke("quotations:convert", id),
  listExpenses: (filter?: DateRangePreset | ReportDateFilter) => ipcRenderer.invoke("expenses:list", filter),
  saveExpense: (input: ExpenseInput) => ipcRenderer.invoke("expenses:save", input),
  deleteExpense: (id: string) => ipcRenderer.invoke("expenses:delete", id),
  profit: (filter: DateRangePreset | ReportDateFilter) => ipcRenderer.invoke("profit:get", filter),
  reports: (filter: DateRangePreset | ReportDateFilter) => ipcRenderer.invoke("reports:get", filter),
  exportReportCsv: (input: { kind: ReportExportKind; filter: DateRangePreset | ReportDateFilter; fileName?: string }) => ipcRenderer.invoke("reports:exportCsv", input),
  getDeveloperDiagnostics: () => ipcRenderer.invoke("developer:getDiagnostics"),
  scanDataHealth: () => ipcRenderer.invoke("developer:scanDataHealth"),
  runSafeRepair: (input: { repairCode: SafeRepairCode }) => ipcRenderer.invoke("developer:runSafeRepair", input),
  getDeveloperLogs: () => ipcRenderer.invoke("developer:getLogs"),
  exportDiagnosticBundle: () => ipcRenderer.invoke("developer:exportDiagnosticBundle"),
  getAppInfo: () => ipcRenderer.invoke("app:getInfo") as Promise<AppInfo>,
  openExternal: (url: string) => ipcRenderer.invoke("app:openExternal", url),
  showItemInFolder: (filePath: string) => ipcRenderer.invoke("app:showItemInFolder", filePath),
  print: (input?: PrintInput) => ipcRenderer.invoke("app:print", input),
  savePdf: (input?: SavePdfInput) => ipcRenderer.invoke("app:savePdf", input),
  createBackup: () => ipcRenderer.invoke("backup:create") as Promise<BackupResult>,
  restoreBackup: () => ipcRenderer.invoke("backup:restore"),
  backupStatus: () => ipcRenderer.invoke("backup:status") as Promise<BackupScheduleStatus>,
  driveStatus: () => ipcRenderer.invoke("drive:status") as Promise<DriveConnectionStatus>,
  connectDrive: (input: { clientId: string; clientSecret: string }) => ipcRenderer.invoke("drive:connect", input.clientId, input.clientSecret) as Promise<DriveConnectionStatus>,
  disconnectDrive: () => ipcRenderer.invoke("drive:disconnect"),
  testDriveConnection: () => ipcRenderer.invoke("drive:testConnection"),
  backupToDriveNow: () => ipcRenderer.invoke("drive:backupNow") as Promise<DriveBackupResult>,
  listDriveBackups: () => ipcRenderer.invoke("drive:listBackups") as Promise<CloudBackupRecord[]>,
  restoreDriveBackup: (fileId: string) => ipcRenderer.invoke("drive:restoreBackup", fileId),
  syncStatus: () => ipcRenderer.invoke("sync:status"),
  connectSyncDevice: (input: SyncConnectInput) => ipcRenderer.invoke("sync:connect", input),
  disconnectSyncDevice: () => ipcRenderer.invoke("sync:disconnect"),
  triggerSync: () => ipcRenderer.invoke("sync:trigger"),
  checkSyncApproval: () => ipcRenderer.invoke("sync:approval-check"),
  listCloudDevices: (input: CloudDeviceOwnerCredentials) => ipcRenderer.invoke("sync:devices-list", input),
  approveCloudDevice: (input: CloudDeviceApprovalInput) => ipcRenderer.invoke("sync:devices-approve", input),
  revokeCloudDevice: (input: CloudDeviceApprovalInput) => ipcRenderer.invoke("sync:devices-revoke", input),
  listSyncConflicts: () => ipcRenderer.invoke("sync:conflicts-list"),
  resolveSyncConflict: (input: { conflictId: string; resolution: SyncConflictResolution }) =>
    ipcRenderer.invoke("sync:conflict-resolve", input),
  onSyncStatus: (callback: (status: unknown) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, status: unknown) => callback(status);
    ipcRenderer.on("sync:status", listener);
    return () => ipcRenderer.removeListener("sync:status", listener);
  },
  openWhatsAppShare: (input: WhatsAppShareInput) => ipcRenderer.invoke("sharing:openWhatsAppShare", input),
  exportCsv: (kind: "invoices" | "customers" | "services" | "inventory" | "enquiries" | "jobCards") => ipcRenderer.invoke("export:csv", kind),
  onDatabaseRestored: (callback: () => void) => {
    const listener = () => callback();
    ipcRenderer.on("database:restored", listener);
    return () => ipcRenderer.removeListener("database:restored", listener);
  },
  onBackupScheduleStatus: (callback: (status: BackupScheduleStatus) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, status: BackupScheduleStatus) => callback(status);
    ipcRenderer.on("backup:schedule-status", listener);
    return () => ipcRenderer.removeListener("backup:schedule-status", listener);
  }
});
